# Generated by Django 3.2.3 on 2021-06-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Urbanity', '0003_product_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item_image',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
