# Generated by Django 3.2.3 on 2021-06-20 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Urbanity', '0004_auto_20210620_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='item_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='number',
        ),
    ]
