# Generated by Django 3.2.3 on 2021-06-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Urbanity', '0007_auto_20210620_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
