# Generated by Django 3.2.3 on 2021-06-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Urbanity', '0008_auto_20210620_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
