# Generated by Django 3.2.3 on 2021-07-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Urbanity', '0012_auto_20210626_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phonenumber',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
