# Generated by Django 3.2.3 on 2021-07-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Urbanity', '0013_customer_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='otp',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
