# Generated by Django 3.2.3 on 2021-07-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Urbanity', '0015_alter_customer_otp'),
    ]

    operations = [
    
    ]
